mayikt:
  name: mayikt
  age: 22
spring:
  http:
    encoding:
#      force: true
      ###模版引擎代码为utf-8
#      charset: UTF-8
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: ftlh
    template-loader-path: classpath:/templates
  thymeleaf:
#    指定模版所在的目录
    prefix: classpath:/templates
#    检查模版路径是否存在
    check-template-location: true
#    开发时,设为false防止重启服务器,线上设置为true,提高性能
    cache: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/fm
    username: root
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver

